
version: 2
jobs:
  checkout-and-install:
    docker:
      - image: circleci/node:9

    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - persist_to_workspace:
          root: ~/
          paths: project
      - save_cache:
          paths:
            - ~/project/node_modules
          key: v1-node-modules-{{ checksum "yarn.lock" }}

  # build:
  #   docker:
  #     - image: circleci/node:9
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Build bundle
  #         command: NODE_ENV=production yarn build
  test-chrome:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests
          command:
            yarn test
            --browser chrome
      - store_test_results:
          path: ./artifacts
      - store_artifacts:
          path: ./artifacts


workflows:
  version: 2
  push:
    jobs:
      - checkout-and-install
      - test-chrome:
          requires:
            - checkout-and-install