
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/react/countdown

    stes:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          command: |
            ls
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/react/countdown/node_modules
          key: v1-node-modules-{{ checksum "yarn.lock" }}

      # run tests!
      # - run: yarn test