
version: 2
jobs:
  checkout-and-install:
    docker:
      - image: circleci/node:9

    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: v1-node-modules-{{ checksum "yarn.lock" }}

      # run tests!
      # - run: yarn test
  build:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build bundle
          command: NODE_ENV=production yarn build