
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/react/countdown

    steps:
      - checkout
      - run:
          command: |
            ls
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            cd react/countdown
            yarn install
      - save_cache:
          paths:
            - ~/react/countdown/node_modules
          key: v1-node-modules-{{ checksum "yarn.lock" }}

      # run tests!
      # - run: yarn test